#!/bin/bash

# Sibyl Oracle Setup Script
# Sets up environment from existing configuration

set -e

echo "🔮 Setting up Sibyl Oracle for Solana..."
echo "=================================================="

# Check for existing config
CONFIG_PATH="/home/carlosmora/clawd/scripts/solana_config.py"
SECRETS_PATH="/home/carlosmora/.secrets/api_keys.env"

if [ ! -f "$CONFIG_PATH" ]; then
    echo "❌ solana_config.py not found at $CONFIG_PATH"
    exit 1
fi

if [ ! -f "$SECRETS_PATH" ]; then
    echo "❌ api_keys.env not found at $SECRETS_PATH"
    exit 1
fi

# Extract values
PRIVATE_KEY=$(grep 'PHANTOM_PRIVATE_KEY' "$CONFIG_PATH" | cut -d'"' -f2)
WALLET_ADDRESS=$(grep 'WALLET_ADDRESS' "$CONFIG_PATH" | cut -d'"' -f2)
DEEPSEEK_KEY=$(grep 'DEEPSEEK_API_KEY' "$SECRETS_PATH" | cut -d'=' -f2)

if [ -z "$PRIVATE_KEY" ] || [ -z "$WALLET_ADDRESS" ]; then
    echo "❌ Could not extract wallet information"
    exit 1
fi

if [ -z "$DEEPSEEK_KEY" ]; then
    echo "⚠️  Could not find DeepSeek API key, using placeholder"
    DEEPSEEK_KEY="sk-5b077f28a1a148989d33cda48e948274"
fi

echo "✅ Found configuration:"
echo "   Wallet: $WALLET_ADDRESS"
echo "   Private Key: $(echo $PRIVATE_KEY | cut -c1-10)..."
echo "   DeepSeek Key: $(echo $DEEPSEEK_KEY | cut -c1-10)..."

# Create .env file
cat > .env << EOF
# Sibyl Oracle - Solana Port
# Auto-generated by setup.sh

# Solana Configuration
SOLANA_RPC=https://api.devnet.solana.com
SOLANA_PRIVATE_KEY=$PRIVATE_KEY

# AI Configuration
DEEPSEEK_API_KEY=$DEEPSEEK_KEY

# Program ID (update after deployment)
ORACLE_PROGRAM_ID=Siby1Oracle111111111111111111111111111111111
EOF

echo ""
echo "✅ Created .env file"
echo ""
echo "📋 Next steps:"
echo "1. Install dependencies: npm install"
echo "2. Build program: npm run build"
echo "3. Deploy: ./deploy.sh devnet"
echo "4. Initialize: node agent/init.js"
echo "5. Run agent: node agent/index.js"
echo ""
echo "🔮 Ready for the Colosseum Hackathon!"